[workspace]
resolver = "2"
members = [
  "installer-cli",
  "installer-core",
  "installer-arch",
  "installer-fedora",
  "installer-debian",
  "wallpaper-downloader",
]

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "z"
