# ~/.config/starship.toml
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$package\
$rust\
$golang\
$nodejs\
$python\
$memory_usage\
$time\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 3
style = "bold blue"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_state]
format = "[\($state( $progress_current/$progress_total)\)]($style) "
style = "bold yellow"

[git_status]
format = "[($all_status$ahead_behind)]($style) "
style = "bold green"
conflicted = "ğŸ³ï¸ "
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
untracked = "?${count} "
stashed = "â‰¡ "
modified = "!${count} "
staged = "+${count} "
renamed = "Â»${count} "
deleted = "âœ˜${count} "

[package]
format = "via [ğŸ“¦ $version](208 bold) "

[rust]
format = "via [ğŸ¦€ $version](red bold) "

[golang]
format = "via [ğŸ¹ $version](cyan bold) "

[nodejs]
format = "via [ğŸ¤– $version](green bold) "

[python]
format = "via [ğŸ $version](yellow bold) "

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 75
symbol = "ğŸ§  "
style = "bold dimmed white"

[time]
format = "ğŸ•’ [$time]($style) "
style = "bold white"
disabled = false

[cmd_duration]
format = "ğŸ•’ [$duration]($style) "
style = "bold yellow"
min_time = 1000

[line_break]
disabled = false

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold yellow)"
